### ISSUE TITLE
UnboundLocalError: local variable 'lw' referenced before assignment

### ISSUE THREAD

**Issue by deepchatterjeeligo** [shaonghosh/sky_tiling#1]
Hi @shaonghosh 
There is a minor error in the if else block linked below
https://github.com/shaonghosh/sky_tiling/blob/master/bin/rankedTilesGenerator.py?utf8=%E2%9C%93#L300-L310

For the plotting code there a linewidth variable __lw__ which has been defined in the __if__ block but has also been called in the __else__ block without assignment, giving an error, if tile centers are not provided.
Can be fixed by defining the __lw__ variable outside the scope of the __if ... else__ block

**Comment by shaonghosh** [comment]
Good catch! Thanks for testing. I will fix this.

**Comment by shaonghosh** [comment]
I think this is resolved now. Could you please verify? I am closing this, if this creep up please reopen a new issue.
